### ISSUE TITLE
Source Code Files Missing?

### ISSUE THREAD

**Issue by jcruzupr** [PacktPublishing/The-Complete-Java-Developer-Course-From-Beginner-to-Master#1]
The Packt course indicates that:  _"The code files and all related files are updated on GitHub at https://github.com/PacktPublishing/The-Complete-Java-Developer-Course-From-Beginner-to-Master"_.  I don't see the source code (.java) files.

**Comment by Sonakshis** [comment]
Hi, 
Thank you so much for bringing this to our attention. We have updated the repository. 

Happy learning!

**Comment by Sonakshis** [comment]
Hi,
Thank you for bringing this to our attention. We have updated the repository.
Happy learning!
